### ISSUE TITLE
what license?

### ISSUE THREAD

**Issue by adibpwd** [david-legend/nimbus#2]
I'm using your template, can I delete the text in the footer and replace it with my product name?

**Comment by david-legend** [comment]
There should be a way that you could link back to me. At least my name should somewhere in the footer with a link leading back to my personal website(davidcobbina.com). That is the only way I benefit from writing all that free code. 
With that being said if you remove it and replace it with your products name, I wouldn't mind. Glad you have found a use for it. Enjoy!

**Comment by david-legend** [comment]
I have added a BSD License to the project

**Comment by adibpwd** [comment]
> 

I will put your name if I use your template, thanks for the answer
