### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by aaronat1** [david-legend/nimbus#3]
Hi, 

I have two errors when run in Chrome (web:)

lib/src/router/widgets/auto_router_delegate.dart:43:43: Error: Required named parameter 'type' must be provided.
        ?.routerReportsNewRouteInformation(

and 

lib/src/visibility_detector_layer.dart:276:21: Error: Too many positional arguments: 1 allowed, but 2 found.
Try removing the extra positional arguments.
    super.addToScene(builder, layerOffset);

Can you help me?

Congratulations. The project is wonderful

Thanks

**Comment by david-legend** [comment]
Haven't run the project in months now. I will give it a look and get back to you.
but looks like it's from auto_route, can you run build runner again for starters or port to the new version if there's any.
Let me know how it goes.
