### ISSUE TITLE
Auto Router giving error with Flutter 2.8.1 Stable

### ISSUE THREAD

**Issue by fundinglife** [david-legend/nimbus#5]
Love the design but cannot get it to work.   I have not changed any of the code other than setting "  visibility_detector: ^0.2.2" to get rid of another error.  I still am getting the following error:

Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
../../Projects/SDK/flutter/.pub-cache/hosted/pub.dartlang.org/auto_route-2.2.0/lib/src/router/widgets/auto_router_delegate.dart:43:43: Error: Required named parameter 'type' must be provided.
        ?.routerReportsNewRouteInformation(
                                          ^
Failed to compile application.

HELP!!!

PS - If I change the auto route to the latest ("auto_route: ^3.2.1" and "auto_route_generator: ^3.2.1") then I get the following error:

Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
lib/presentation/routes/router.gr.dart:20:9: Error: No named parameter with the name 'builder'.
        builder: (_) {
        ^^^^^^^
../../OneDrive/Projects/SDK/flutter/.pub-cache/hosted/pub.dartlang.org/auto_route-3.2.1/lib/src/router/auto_route_page.dart:62:3: Context: Found this candidate, but the arguments don't match.
  MaterialPageX({
  ^^^^^^^^^^^^^
Failed to compile application.

**Comment by david-legend** [comment]
What flutter version are you on ??

**Comment by fundinglife** [comment]
Flutter 2.8.1 Stable Channel

**Comment by david-legend** [comment]
Haven't run it myself in a long time. Will take a look and get back to you.

**Comment by fundinglife** [comment]
Thank you so much!  Looking at the code, I like the way you set everything up!

**Comment by david-legend** [comment]
Welcome, I'll comment soon when I get it to work. But it's dawn here. So I won't start work till a few hours time

**Comment by fundinglife** [comment]
Perfect, will wait for your response!

**Comment by fundinglife** [comment]
Any luck?

**Comment by fundinglife** [comment]
Figured it out... but thanks for all your help!

**Comment by david-legend** [comment]
So sorry, got lazy. I just looked at it and got it to work. Sorry about the late reply
